clear
clc

rng('shuffle')

grid = [1000, 1000]; % in m
bs_count = 256;
mec_count = 64;
mec_clock = 4*2.6; % GHz

uplink_bandwidth_4g = 10; % in MHz
uplink_bandwidth_5g = 200; % in MHz

downlink_bandwidth_4g = 10; % in MHz
downlink_bandwidth_5g = 200; % in MHz

backhaul_bandwidth_4g = 20; % in MHz
backhaul_bandwidth_5g = 1000; % in MHz

uplink_carrier_frequency_4g = 3.7; % in GHz 
uplink_carrier_frequency_5g = 40; % in GHz 

downlink_carrier_frequency_4g = 3.3; % in GHz
downlink_carrier_frequency_5g = 28; % in GHz

backhaul_carrier_frequency_4g = 4.5; % in GHz
backhaul_carrier_frequency_5g = 60; % in GHz

uplink_power = 23; % in dBm
downlink_power = 30; % in dBm
backhaul_power = 40; %in dBm

noise_spectral_density = -174; % in dBm/Hz

user_count = 100;

req_size = 10; % in MB

BS = BaseStationsSetup(grid, 16, bs_count, mec_count, mec_clock, ...
    uplink_bandwidth_4g, uplink_bandwidth_5g, ...
    downlink_bandwidth_4g, downlink_bandwidth_5g, ...
    backhaul_bandwidth_4g, backhaul_bandwidth_5g, ...
    uplink_carrier_frequency_4g, uplink_carrier_frequency_5g, ...
    downlink_carrier_frequency_4g, downlink_carrier_frequency_5g, ...
    backhaul_carrier_frequency_4g, backhaul_carrier_frequency_5g, ...
    uplink_power, downlink_power, backhaul_power, noise_spectral_density);

BS = calculateRadii(BS, ...
    uplink_power, downlink_power, backhaul_power, ...
    uplink_carrier_frequency_4g, downlink_carrier_frequency_4g, backhaul_carrier_frequency_4g, ...
    uplink_carrier_frequency_5g, downlink_carrier_frequency_5g, backhaul_carrier_frequency_5g, ...
    uplink_bandwidth_4g, uplink_bandwidth_5g, ...
    downlink_bandwidth_4g, downlink_bandwidth_5g, ...
    backhaul_bandwidth_4g, backhaul_bandwidth_5g, ...
    noise_spectral_density);


BS2 = BaseStationsSetup(grid, 16, bs_count, mec_count, mec_clock, ...
    uplink_bandwidth_4g, uplink_bandwidth_5g, ...
    downlink_bandwidth_4g, downlink_bandwidth_5g, ...
    backhaul_bandwidth_4g, backhaul_bandwidth_5g, ...
    uplink_carrier_frequency_4g*1.2, uplink_carrier_frequency_5g*1.2, ...
    downlink_carrier_frequency_4g*1.2, downlink_carrier_frequency_5g*1.2, ...
    backhaul_carrier_frequency_4g, backhaul_carrier_frequency_5g*1.2, ...
    uplink_power, downlink_power, backhaul_power, noise_spectral_density);

BS2 = calculateRadii(BS2, ...
    uplink_power, downlink_power, backhaul_power, ...
    uplink_carrier_frequency_4g*1.2, downlink_carrier_frequency_4g*1.2, backhaul_carrier_frequency_4g*1.2, ...
    uplink_carrier_frequency_5g*1.2, downlink_carrier_frequency_5g*1.2, backhaul_carrier_frequency_5g*1.2, ...
    uplink_bandwidth_4g, uplink_bandwidth_5g, ...
    downlink_bandwidth_4g, downlink_bandwidth_5g, ...
    backhaul_bandwidth_4g, backhaul_bandwidth_5g, ...
    noise_spectral_density);


BS3 = BaseStationsSetup(grid, 16, bs_count, mec_count, mec_clock, ...
    uplink_bandwidth_4g, uplink_bandwidth_5g, ...
    downlink_bandwidth_4g, downlink_bandwidth_5g, ...
    backhaul_bandwidth_4g, backhaul_bandwidth_5g, ...
    uplink_carrier_frequency_4g*1.4, uplink_carrier_frequency_5g*1.4, ...
    downlink_carrier_frequency_4g*1.4, downlink_carrier_frequency_5g*1.4, ...
    backhaul_carrier_frequency_4g*1.4, backhaul_carrier_frequency_5g*1.4, ...
    uplink_power, downlink_power, backhaul_power, noise_spectral_density);

BS3 = calculateRadii(BS3, ...
    uplink_power, downlink_power, backhaul_power, ...
    uplink_carrier_frequency_4g*1.4, downlink_carrier_frequency_4g*1.4, backhaul_carrier_frequency_4g*1.4, ...
    uplink_carrier_frequency_5g*1.4, downlink_carrier_frequency_5g*1.4, backhaul_carrier_frequency_5g*1.4, ...
    uplink_bandwidth_4g, uplink_bandwidth_5g, ...
    downlink_bandwidth_4g, downlink_bandwidth_5g, ...
    backhaul_bandwidth_4g, backhaul_bandwidth_5g, ...
    noise_spectral_density);


BS4 = BaseStationsSetup(grid, 16, bs_count, mec_count, mec_clock, ...
    uplink_bandwidth_4g, uplink_bandwidth_5g, ...
    downlink_bandwidth_4g, downlink_bandwidth_5g, ...
    backhaul_bandwidth_4g, backhaul_bandwidth_5g, ...
    uplink_carrier_frequency_4g*1.6, uplink_carrier_frequency_5g*1.6, ...
    downlink_carrier_frequency_4g*1.6, downlink_carrier_frequency_5g*1.6, ...
    backhaul_carrier_frequency_4g*1.6, backhaul_carrier_frequency_5g*1.6, ...
    uplink_power, downlink_power, backhaul_power, noise_spectral_density);

BS4 = calculateRadii(BS4, ...
    uplink_power, downlink_power, backhaul_power, ...
    uplink_carrier_frequency_4g*1.6, downlink_carrier_frequency_4g*1.6, backhaul_carrier_frequency_4g*1.6, ...
    uplink_carrier_frequency_5g*1.6, downlink_carrier_frequency_5g*1.6, backhaul_carrier_frequency_5g*1.6, ...
    uplink_bandwidth_4g, uplink_bandwidth_5g, ...
    downlink_bandwidth_4g, downlink_bandwidth_5g, ...
    backhaul_bandwidth_4g, backhaul_bandwidth_5g, ...
    noise_spectral_density);
  %----- test 4:  -----%

avg = [];
[avg(1,1), avg(1,2), avg(1,3), avg(1,4), avg(1,5)] = runSimulation(10, BS, user_count, grid, req_size);

[avg(2,1), avg(2,2), avg(2,3), avg(2,4), avg(2,5)] = runSimulation(10, BS2, user_count, grid, req_size);

[avg(3,1), avg(3,2), avg(3,3), avg(3,4), avg(3,5)] = runSimulation(10, BS3, user_count, grid, req_size);

[avg(4,1), avg(4,2), avg(4,3), avg(4,4), avg(4,5)] = runSimulation(10, BS4, user_count, grid, req_size);


avg(:,5) = [];
figure(1)
names = {'*1'; '*1.2'; '*1.4'; '*1.6'};
bar(avg, 'stacked');
set(gca,'xtick', 1:4,'xticklabel',names)
ylabel('Latency (in s)')
legend({'uplink', 'processing', 'downlink', 'backhaul'},'Location','northeast')
title('Average Total Delay vs Increasing Carrier Frequency')
hold off

figure(2)
x = [1 2];
plot(x, avg(1:2,:))
legend({'uplink', 'processing', 'downlink', 'backhaul'},'Location','northeast')
title('Average Delay vs Increasing # of Users')
xlabel('All connected vs Not all connected') 
ylabel('Latency (in s)') 
hold off
   %-------------------------------------------------%